#!/usr/bin/env python

import os
import pickle
import argparse

from lymphkill.calc_blood_kill import calc_kill_frac, regeneration

if __name__=='__main__':
	parser = argparse.ArgumentParser('Blood kill calculation. Requires blood dose')
	parser.add_argument('directory', type=str, help='The patient directory to look in')
	args = parser.parse_args()
	
	with open(os.path.join(args.directory, 'blood_hist.pickle'), 'rb') as infile:
		counts, edges = pickle.load(infile)
	percent = calc_kill_frac(counts, edges)
	percent = regeneration(percent, 0.001, day=25)
	print('Total Percent Kill:\t%g' % percent)
