#!/usr/bin/env python

import os
import argparse
import pickle

from lymphkill.file_utils import find_dicom_directory
from lymphkill.structure_loading import load_structures



if __name__=='__main__':
	parser = argparse.ArgumentParser('Loading in contoured structures')
	parser.add_argument('directory', type=str, help='The patient directory to look in')
	args = parser.parse_args()

	directory = find_dicom_directory(args.directory)
	contours = load_structures(directory)
	for i in contours['ROIName']:
		print(i)
	outfile = open(os.path.join(args.directory, 'contours.pickle'), 'wb')
	pickle.dump(contours, outfile)
	outfile.close()
